<?php

namespace ContainerHbbnbMV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3RP2_AyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3RP2.Ay' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3RP2.Ay'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.xYZTOMA', 'get_ServiceLocator_XYZTOMAService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.xYZTOMA', 'get_ServiceLocator_XYZTOMAService', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.4jTisVh', 'get_ServiceLocator_4jTisVhService', true],
            'App\\Controller\\Admin\\BlogController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.Q0_vU_b', 'get_ServiceLocator_Q0VUBService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.kNjWwTq', 'get_ServiceLocator_KNjWwTqService', true],
            'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\BlogController::search' => ['privates', '.service_locator.4jTisVh', 'get_ServiceLocator_4jTisVhService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.c6tjZHl', 'get_ServiceLocator_C6tjZHlService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.4bEKtcl', 'get_ServiceLocator_4bEKtclService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.xYZTOMA', 'get_ServiceLocator_XYZTOMAService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.xYZTOMA', 'get_ServiceLocator_XYZTOMAService', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.4jTisVh', 'get_ServiceLocator_4jTisVhService', true],
            'App\\Controller\\Admin\\BlogController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.Q0_vU_b', 'get_ServiceLocator_Q0VUBService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.kNjWwTq', 'get_ServiceLocator_KNjWwTqService', true],
            'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.E6OewJ8', 'get_ServiceLocator_E6OewJ8Service', true],
            'App\\Controller\\BlogController:search' => ['privates', '.service_locator.4jTisVh', 'get_ServiceLocator_4jTisVhService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.c6tjZHl', 'get_ServiceLocator_C6tjZHlService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.4bEKtcl', 'get_ServiceLocator_4bEKtclService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::new' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\BlogController::commentForm' => '?',
            'App\\Controller\\BlogController::commentNew' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::postShow' => '?',
            'App\\Controller\\BlogController::search' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:new' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\BlogController:commentForm' => '?',
            'App\\Controller\\BlogController:commentNew' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:postShow' => '?',
            'App\\Controller\\BlogController:search' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
