<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExx41Ia\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExx41Ia/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExx41Ia.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExx41Ia\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerExx41Ia\App_KernelDevDebugContainer([
    'container.build_hash' => 'Exx41Ia',
    'container.build_id' => 'ec2d8e5c',
    'container.build_time' => 1752266735,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExx41Ia');
